version: '2'

services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./ssl:/ssl
            - ./log:/var/log/nginx
        networks:
            - code-network
    php:
        image: liquuid-prod
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        volumes:
            - ./src:/code
        networks:
            - code-network
    db:
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=pass 
        volumes:
            - ./db-data:/var/lib/mysql
        networks:
            - code-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8888:80"
        environment:
            - MYSQL_ROOT_PASSWORD=pass 
        networks:
            - code-network
    
    wpcli:
        image: tatemz/wp-cli
        volumes_from:
            - php
            - db
        entrypoint: wp  
        command: "--info"
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
